-- Generated by ./gradlew exportJpaSchema
-- Source: current JPA entity mappings (PostgreSQL dialect)

create table breed (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        size varchar(10) not null check (size in ('SMALL','MEDIUM','LARGE')),
        name varchar(50) not null,
        primary key (id)
    );

    create table chat_participant (
        chat_room_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        joined_at timestamp(6) not null,
        last_read_message_id bigint,
        left_at timestamp(6),
        member_id bigint not null,
        updated_at timestamp(6) not null,
        walk_confirm_state varchar(20) not null check (walk_confirm_state in ('UNCONFIRMED','CONFIRMED')),
        primary key (id),
        constraint uk_chat_participant_room_member unique (chat_room_id, member_id)
    );

    create table chat_participant_pet (
        chat_participant_id bigint not null,
        id bigint generated by default as identity,
        pet_id bigint not null,
        primary key (id),
        constraint uk_chat_participant_pet unique (chat_participant_id, pet_id)
    );

    create table chat_review (
        score integer not null,
        chat_room_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        reviewee_id bigint not null,
        reviewer_id bigint not null,
        updated_at timestamp(6) not null,
        comment varchar(1000),
        primary key (id),
        constraint uk_chat_review_room_reviewer_reviewee unique (chat_room_id, reviewer_id, reviewee_id)
    );

    create table chat_room (
        walk_confirmed boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_message_at timestamp(6) with time zone,
        thread_id bigint,
        updated_at timestamp(6) not null,
        version bigint,
        chat_type varchar(20) not null check (chat_type in ('DIRECT','GROUP')),
        origin varchar(20) not null check (origin in ('DM','WALK','LOST_PET')),
        status varchar(20) not null check (status in ('ACTIVE','CLOSED')),
        room_title varchar(200),
        primary key (id)
    );

    create table comment (
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        post_id bigint not null,
        updated_at timestamp(6) not null,
        content varchar(500) not null,
        primary key (id)
    );

    create table lost_pet_match (
        similarity_total numeric(5,4) not null,
        approved_at timestamp(6),
        approved_by_member_id bigint,
        chat_room_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        invalidated_at timestamp(6),
        lost_pet_id bigint not null,
        matched_at timestamp(6) not null,
        sighting_id bigint not null,
        updated_at timestamp(6) not null,
        invalidated_reason varchar(40) check (invalidated_reason in ('REPORT_RESOLVED','SIGHTING_CLOSED','MANUAL_CANCEL')),
        status varchar(40) not null check (status in ('PENDING_APPROVAL','APPROVED','PENDING_CHAT_LINK','CHAT_LINKED','INVALIDATED','REJECTED')),
        primary key (id)
    );

    create table lost_pet_report (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_seen_at timestamp(6) not null,
        owner_id bigint not null,
        resolved_at timestamp(6),
        updated_at timestamp(6) not null,
        status varchar(30) not null check (status in ('ACTIVE','RESOLVED','CLOSED')),
        breed varchar(100),
        pet_name varchar(100) not null,
        photo_url varchar(500) not null,
        description varchar(2000),
        last_seen_location varchar(255) not null,
        primary key (id)
    );

    create table lost_pet_search_candidate (
        rank_order integer not null,
        score_distance numeric(6,5) not null,
        score_recency numeric(6,5) not null,
        score_similarity numeric(6,5) not null,
        score_total numeric(6,5) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        session_id bigint not null,
        sighting_id bigint not null,
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('CANDIDATE','APPROVED')),
        primary key (id)
    );

    create table lost_pet_search_session (
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        lost_pet_id bigint not null,
        owner_id bigint not null,
        updated_at timestamp(6) not null,
        query_mode varchar(20) not null,
        query_image_url varchar(1000),
        query_text varchar(2000),
        primary key (id)
    );

    create table member (
        age integer,
        is_timeline_public boolean not null,
        is_verified boolean not null,
        manner_score_count integer not null,
        manner_score_sum integer not null,
        mbti varchar(4),
        value numeric(38,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        nickname_changed_at timestamp(6),
        updated_at timestamp(6) not null,
        nickname varchar(10) not null unique,
        phone varchar(13),
        email varchar(255) not null unique,
        gender varchar(255) check (gender in ('MALE','FEMALE','UNKNOWN')),
        linked_nickname varchar(255),
        member_type varchar(255) not null check (member_type in ('PET_OWNER','NON_PET_OWNER','ADMIN')),
        password varchar(255),
        personality varchar(255),
        profile_image_url varchar(255),
        self_introduction varchar(255),
        status varchar(255) not null check (status in ('ACTIVE','INACTIVE','BANNED')),
        primary key (id)
    );

    create table member_follow (
        created_at timestamp(6) not null,
        follower_id bigint not null,
        following_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        primary key (id),
        unique (follower_id, following_id)
    );

    create table member_personality (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        personality_type_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id),
        unique (member_id, personality_type_id)
    );

    create table member_personality_type (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        code varchar(30) not null unique,
        name varchar(50) not null,
        primary key (id)
    );

    create table message (
        chat_room_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        sender_id bigint not null,
        sent_at timestamp(6) with time zone not null,
        updated_at timestamp(6) not null,
        message_type varchar(20) not null check (message_type in ('USER','SYSTEM')),
        client_message_id varchar(100),
        content varchar(500) not null,
        primary key (id),
        constraint uk_message_room_sender_client unique (chat_room_id, sender_id, client_message_id)
    );

    create table notification (
        is_read boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        recipient_member_id bigint not null,
        reference_id bigint,
        updated_at timestamp(6) not null,
        reference_type varchar(30),
        type varchar(30) not null check (type in ('CHAT_NEW_MESSAGE','WALK_CONFIRM','WALK_APPLICATION','COMMENT_ON_POST')),
        title varchar(200) not null,
        message varchar(500) not null,
        primary key (id)
    );

    create table personality (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        code varchar(20) not null unique,
        name varchar(20) not null,
        primary key (id)
    );

    create table pet (
        age integer not null,
        is_main boolean not null,
        is_neutered boolean not null,
        mbti varchar(4),
        breed_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6) not null,
        gender varchar(10) not null check (gender in ('MALE','FEMALE')),
        name varchar(10) not null,
        size varchar(10) not null check (size in ('SMALL','MEDIUM','LARGE')),
        photo_url varchar(255),
        primary key (id)
    );

    create table pet_personality (
        id bigint generated by default as identity,
        personality_id bigint,
        pet_id bigint,
        primary key (id)
    );

    create table pet_walking_style (
        id bigint generated by default as identity,
        pet_id bigint,
        walking_style_id bigint,
        primary key (id)
    );

    create table post (
        comment_count integer not null,
        like_count integer not null,
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint,
        content varchar(2000) not null,
        primary key (id)
    );

    create table post_image_url (
        post_id bigint not null,
        image_url varchar(255)
    );

    create table post_like (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        post_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id),
        constraint uk_post_like_post_member unique (post_id, member_id)
    );

    create table refresh_token (
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        revoked_at timestamp(6),
        updated_at timestamp(6) not null,
        token_hash varchar(255) not null unique,
        primary key (id)
    );

    create table sighting (
        created_at timestamp(6) not null,
        finder_id bigint not null,
        found_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        status varchar(30) not null check (status in ('OPEN','CLOSED')),
        photo_url varchar(500) not null,
        memo varchar(2000),
        found_location varchar(255) not null,
        primary key (id)
    );

    create table thread (
        allow_non_pet_owner boolean not null,
        is_visible_always boolean not null,
        latitude numeric(10,6) not null,
        longitude numeric(11,6) not null,
        max_participants integer not null,
        walk_date date not null,
        author_id bigint not null,
        created_at timestamp(6) not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        start_time timestamp(6) not null,
        updated_at timestamp(6) not null,
        version bigint,
        chat_type varchar(20) not null check (chat_type in ('INDIVIDUAL','GROUP')),
        status varchar(20) not null check (status in ('RECRUITING','EXPIRED','COMPLETED','DELETED')),
        title varchar(30) not null,
        place_name varchar(200) not null,
        address varchar(500),
        description varchar(500) not null,
        primary key (id)
    );

    create table thread_application (
        chat_room_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        thread_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint,
        status varchar(20) not null check (status in ('JOINED','CANCELED')),
        primary key (id),
        unique (thread_id, member_id)
    );

    create table thread_application_pet (
        application_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        pet_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id),
        unique (application_id, pet_id)
    );

    create table thread_filter (
        is_required boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        thread_id bigint not null,
        updated_at timestamp(6) not null,
        type varchar(50) not null,
        values_json varchar(2000) not null,
        primary key (id)
    );

    create table thread_pet (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        pet_id bigint not null,
        thread_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id),
        unique (thread_id, pet_id)
    );

    create table timeline_event (
        deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        occurred_at timestamp(6) not null,
        reference_id bigint not null,
        updated_at timestamp(6) not null,
        event_type varchar(50) not null check (event_type in ('WALK_THREAD_CREATED','WALKING_SESSION_STARTED','WALKING_SESSION_COMPLETED','POST_CREATED','LOST_PET_REPORT_CREATED','SIGHTING_CREATED','WALK_DIARY_CREATED')),
        title varchar(100),
        summary varchar(500),
        thumbnail_url varchar(500),
        primary key (id),
        unique (event_type, reference_id)
    );

    create table walk_diary (
        is_public boolean not null,
        walk_date date not null,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        thread_id bigint,
        updated_at timestamp(6) not null,
        version bigint,
        title varchar(120) not null,
        content varchar(300) not null,
        primary key (id)
    );

    create table walk_diary_photo_url (
        display_order integer not null,
        walk_diary_id bigint not null,
        photo_url varchar(1000) not null,
        primary key (display_order, walk_diary_id)
    );

    create table walking_session (
        created_at timestamp(6) not null,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        last_heartbeat_at timestamp(6) not null,
        member_id bigint not null,
        started_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('ACTIVE','ENDED')),
        primary key (id)
    );

    create table walking_style (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        code varchar(20) not null unique,
        name varchar(20) not null,
        primary key (id)
    );

    create index idx_message_room_id_id 
       on message (chat_room_id, id);

    alter table if exists lost_pet_match 
       add constraint FKpmmf5j8qbvs8k6n4e506pb6mg 
       foreign key (lost_pet_id) 
       references lost_pet_report;

    alter table if exists lost_pet_match 
       add constraint FKi8x9rfv35kv7053rf5uru3qpc 
       foreign key (sighting_id) 
       references sighting;

    alter table if exists lost_pet_search_candidate 
       add constraint FKa5pvyfbo2m35nf8yg1n8p1jfu 
       foreign key (session_id) 
       references lost_pet_search_session;

    alter table if exists lost_pet_search_candidate 
       add constraint FKa3m6jbgg27pf8n22mh0s8la6h 
       foreign key (sighting_id) 
       references sighting;

    alter table if exists lost_pet_search_session 
       add constraint FK7tubxsxrw4k7io1ymla9gnrx1 
       foreign key (lost_pet_id) 
       references lost_pet_report;

    alter table if exists member_personality 
       add constraint FK6mgh8yno1u99t9dd6bdgf9hy8 
       foreign key (member_id) 
       references member;

    alter table if exists member_personality 
       add constraint FKhrcvrm5g5sdhr8s3xjgqj96fq 
       foreign key (personality_type_id) 
       references member_personality_type;

    alter table if exists pet 
       add constraint FKiqbjbaml7gtwulqptktmsi5dc 
       foreign key (breed_id) 
       references breed;

    alter table if exists pet_personality 
       add constraint FKmxkk1ev7v9mdcd6nja7olbdei 
       foreign key (personality_id) 
       references personality;

    alter table if exists pet_personality 
       add constraint FKmb5q23owdl4ix85o2x21xd3x5 
       foreign key (pet_id) 
       references pet;

    alter table if exists pet_walking_style 
       add constraint FK367nh0b1agmb49rms77dv59t6 
       foreign key (pet_id) 
       references pet;

    alter table if exists pet_walking_style 
       add constraint FKobmxfi26xjosdse4yevw6n022 
       foreign key (walking_style_id) 
       references walking_style;

    alter table if exists post_image_url 
       add constraint FK8k3tbuejh2w1rojdjjh1e1di8 
       foreign key (post_id) 
       references post;

    alter table if exists refresh_token 
       add constraint FK5gdbafb2i76hk1ai18ah6an4w 
       foreign key (member_id) 
       references member;

    alter table if exists walk_diary_photo_url 
       add constraint FK334s5o1asvy26apd8xxrlo4cc 
       foreign key (walk_diary_id) 
       references walk_diary;
