export interface DogBreed {
  en: string;
  ko: string;
  jp: string;
}

export const DOG_BREEDS: DogBreed[] = [
  // --- Popular & Common ---
  { en: "Golden Retriever", ko: "골든 리트리버", jp: "ゴールデン・レトリバー" },
  { en: "Labrador Retriever", ko: "래브라도 리트리버", jp: "ラブラドール・レトリバー" },
  { en: "German Shepherd", ko: "저먼 셰퍼드", jp: "ジャーマン・シェパード" },
  { en: "Poodle", ko: "푸들", jp: "プードル" },
  { en: "Bulldog", ko: "불독", jp: "ブルドッグ" },
  { en: "French Bulldog", ko: "프렌치 불독", jp: "フレンチ・ブルドッグ" },
  { en: "Beagle", ko: "비글", jp: "ビーグル" },
  { en: "Rottweiler", ko: "로트와일러", jp: "ロットワイラー" },
  { en: "Pug", ko: "퍼그", jp: "パグ" },
  { en: "Dachshund", ko: "닥스훈트", jp: "ダックスフンド" },
  { en: "Yorkshire Terrier", ko: "요크셔 테리어", jp: "ヨークシャー・テリア" },
  { en: "Chihuahua", ko: "치와와", jp: "チワワ" },
  { en: "Shih Tzu", ko: "시추", jp: "シーズー" },
  { en: "Pomeranian", ko: "포메라니안", jp: "ポメラニアン" },
  { en: "Border Collie", ko: "보더 콜리", jp: "ボーダー・コリー" },
  { en: "Siberian Husky", ko: "시베리안 허스키", jp: "シベリアン・ハスキー" },
  { en: "Bichon Frise", ko: "비숑 프리제", jp: "ビション・フリーゼ" },
  { en: "Maltese", ko: "말티즈", jp: "マルチーズ" },
  { en: "Samoyed", ko: "사모예드", jp: "サモエド" },
  { en: "Welsh Corgi", ko: "웰시 코기", jp: "ウェルシュ・コーギー" },
  
  // --- Asian & Native Breeds ---
  { en: "Shiba Inu", ko: "시바견", jp: "柴犬" },
  { en: "Akita Inu", ko: "아키타견", jp: "秋田犬" },
  { en: "Jindo Dog", ko: "진돗개", jp: "珍島犬" },
  { en: "Pungsan Dog", ko: "풍산개", jp: "豊山犬" },
  { en: "Sapsali", ko: "삽살개", jp: "サプサル犬" },
  { en: "Donggyeongi", ko: "동경이", jp: "東庚犬" },
  { en: "Jeju Dog", ko: "제주개", jp: "済州犬" },
  { en: "Tosa Inu", ko: "도사견", jp: "土佐犬" },
  { en: "Kishu Ken", ko: "기슈견", jp: "紀州犬" },
  { en: "Kai Ken", ko: "카이견", jp: "甲斐犬" },
  { en: "Hokkaido Ken", ko: "홋카이도견", jp: "北海道犬" },
  { en: "Shikoku Ken", ko: "시코쿠견", jp: "四国犬" },
  { en: "Japanese Chin", ko: "재패니즈 친", jp: "狆" },
  { en: "Japanese Terrier", ko: "재패니즈 테리어", jp: "日本テリア" },
  { en: "Japanese Spitz", ko: "재패니즈 스피츠", jp: "日本スピッツ" },
  { en: "Shar Pei", ko: "샤페이", jp: "シャー・ペイ" },
  { en: "Chow Chow", ko: "차우차우", jp: "チャウ・チャウ" },
  { en: "Pekingese", ko: "페키니즈", jp: "ペキニーズ" },
  { en: "Lhasa Apso", ko: "라사 압소", jp: "ラサ・アプソ" },
  { en: "Tibetan Spaniel", ko: "티베탄 스패니얼", jp: "チベタン・スパニエル" },
  { en: "Tibetan Terrier", ko: "티베탄 테리어", jp: "チベタン・テリア" },

  // --- Working & Guard Dogs ---
  { en: "Doberman", ko: "도베르만", jp: "ドーベルマン" },
  { en: "Boxer", ko: "복서", jp: "ボクサー" },
  { en: "Great Dane", ko: "그레이트 데인", jp: "グレート・デーン" },
  { en: "Bernese Mountain Dog", ko: "버니즈 마운틴 독", jp: "バーニーズ・マウンテン・ドッグ" },
  { en: "Saint Bernard", ko: "세인트 버나드", jp: "セント・バーナード" },
  { en: "Mastiff", ko: "마스티프", jp: "マスティフ" },
  { en: "Bullmastiff", ko: "불마스티프", jp: "ブルマスティフ" },
  { en: "Cane Corso", ko: "카네코르소", jp: "カネ・コルソ" },
  { en: "Newfoundland", ko: "뉴펀들랜드", jp: "ニューファンドランド" },
  { en: "Portuguese Water Dog", ko: "포르투갈 워터 독", jp: "ポルトガル・ウォーター・ドッグ" },
  { en: "Giant Schnauzer", ko: "자이언트 슈나우저", jp: "ジャイアント・シュナウザー" },
  { en: "Standard Schnauzer", ko: "스탠다드 슈나우저", jp: "スタンダード・シュナウザー" },
  { en: "Dogo Argentino", ko: "도고 아르젠티노", jp: "ドゴ・アルヘンティーノ" },
  { en: "Greater Swiss Mountain Dog", ko: "그레이터 스위스 마운틴 독", jp: "グレーター・スイス・マウンテン・ドッグ" },

  // --- Hounds ---
  { en: "Afghan Hound", ko: "아프간 하운드", jp: "アフガン・ハウンド" },
  { en: "Greyhound", ko: "그레이하운드", jp: "グレーハウンド" },
  { en: "Italian Greyhound", ko: "이탈리안 그레이하운드", jp: "イタリアン・グレーハウンド" },
  { en: "Whippet", ko: "휘핏", jp: "ウィペット" },
  { en: "Basenji", ko: "바센지", jp: "バセンジー" },
  { en: "Borzoi", ko: "보르조이", jp: "ボルゾイ" },
  { en: "Saluki", ko: "살루키", jp: "サルーキ" },
  { en: "Irish Wolfhound", ko: "아이리시 울프하운드", jp: "アイリッシュ・ウルフハウンド" },
  { en: "Bloodhound", ko: "블러드하운드", jp: "ブラッドハウンド" },
  { en: "Basset Hound", ko: "바셋 하운드", jp: "バセット・ハウンド" },
  { en: "Rhodesian Ridgeback", ko: "로디지안 리지백", jp: "ローデシアン・リッジバック" },
  { en: "Pharaoh Hound", ko: "파라오 하운드", jp: "ファラオ・ハウンド" },

  // --- Sporting Breeds ---
  { en: "Cocker Spaniel", ko: "코카 스패니얼", jp: "コッカー・スパニエル" },
  { en: "English Cocker Spaniel", ko: "잉글리시 코카 스패니얼", jp: "イングリッシュ・コッカー・スパニエル" },
  { en: "Springer Spaniel", ko: "스프링거 스패니얼", jp: "スプリンガー・スパニエル" },
  { en: "Vizsla", ko: "비즐라", jp: "ビズラ" },
  { en: "Weimaraner", ko: "바이마라너", jp: "ワイマラナー" },
  { en: "Brittany", ko: "브리타니", jp: "ブリタニー" },
  { en: "Pointer", ko: "포인터", jp: "ポインター" },
  { en: "German Shorthaired Pointer", ko: "저먼 쇼트헤어드 포인터", jp: "ジャーマン・ショートヘアード・ポインター" },
  { en: "Irish Setter", ko: "아이리시 세터", jp: "アイリッシュ・セッター" },
  { en: "English Setter", ko: "잉글리시 세터", jp: "イングリッシュ・セッター" },
  { en: "Gordon Setter", ko: "고든 세터", jp: "ゴードン・セッター" },

  // --- Terriers ---
  { en: "Jack Russell Terrier", ko: "잭 러셀 테리어", jp: "ジャック・ラッセル・テリア" },
  { en: "Bull Terrier", ko: "불 테리어", jp: "ブル・テリア" },
  { en: "Staffordshire Bull Terrier", ko: "스태퍼드셔 불 테리어", jp: "スタッフォードシャー・ブル・テリア" },
  { en: "Miniature Schnauzer", ko: "미니어처 슈나우저", jp: "ミニチュア・シュナウザー" },
  { en: "Scottish Terrier", ko: "스코티시 테리어", jp: "スコティッシュ・テリア" },
  { en: "Airedale Terrier", ko: "에어데일 테리어", jp: "エアデール・テリア" },
  { en: "West Highland White Terrier", ko: "화이트 테리어", jp: "ウエスト・ハイランド・ホワイト・テリア" },
  { en: "Cairn Terrier", ko: "케언 테리어", jp: "ケアーン・テリア" },
  { en: "Soft Coated Wheaten Terrier", ko: "소프트 코티드 휘튼 테리어", jp: "ソフトコーテッド・ウィートン・テリア" },
  { en: "Border Terrier", ko: "보더 테리어", jp: "ボーダー・テリア" },
  { en: "Australian Terrier", ko: "오스트레일리안 테리어", jp: "オーストラリアン・テリア" },
  { en: "Norfolk Terrier", ko: "노포크 테리어", jp: "ノーフォーク・テリア" },
  { en: "Norwich Terrier", ko: "노리치 테리어", jp: "ノーリッチ・テリア" },

  // --- Herding Breeds ---
  { en: "Shetland Sheepdog", ko: "셔틀랜드 쉽독", jp: "シェットランド・シープドッグ" },
  { en: "Australian Shepherd", ko: "오스트레일리안 셰퍼드", jp: "オーストラリアン・シェパード" },
  { en: "Old English Sheepdog", ko: "올드 잉글리시 쉽독", jp: "オールド・イングリッシュ・シープドッグ" },
  { en: "Collie", ko: "콜리", jp: "コリー" },
  { en: "Bearded Collie", ko: "비어디드 콜리", jp: "ビアデッド・コリー" },
  { en: "Belgian Malinois", ko: "벨지안 말리노이즈", jp: "ベルジアン・マリノア" },
  { en: "Belgian Sheepdog", ko: "벨지안 쉽독", jp: "ベルジアン・シェパード・ドッグ" },
  { en: "Bouvier des Flandres", ko: "부비에 데 플랑드르", jp: "ブービエ・デ・フランダース" },
  { en: "Briard", ko: "브리아드", jp: "ブリアード" },
  { en: "Pembroke Welsh Corgi", ko: "펨브록 웰시 코기", jp: "ペンブローク・ウェルシュ・コーギー" },
  { en: "Cardigan Welsh Corgi", ko: "카디건 웰시 코기", jp: "カーディガン・ウェルシュ・コーギー" },

  // --- Toy Breeds ---
  { en: "Papillon", ko: "파피용", jp: "パピヨン" },
  { en: "Cavalier King Charles Spaniel", ko: "카발리에 킹 찰스 스파니엘", jp: "キャバリア・キングチャールズ・スパニエル" },
  { en: "Miniature Pinscher", ko: "미니어처 핀셔", jp: "ミニチュア・ピンシャー" },
  { en: "Havanese", ko: "하바네즈", jp: "ハバニーズ" },
  { en: "Brussels Griffon", ko: "브뤼셀 그리폰", jp: "ブリュッセル・グリフォン" },
  { en: "Japanese Chin", ko: "재패니즈 친", jp: "狆" },
  { en: "Chinese Crested", ko: "차이니즈 크레스티드", jp: "チャイニーズ・クレステッド・ドッグ" },
  { en: "Silky Terrier", ko: "실키 테리어", jp: "シルキー・テリア" },
  { en: "Toy Fox Terrier", ko: "토이 폭스 테리어", jp: "トイ・フォックス・テリア" },

  // --- More Breeds ---
  { en: "Dalmatian", ko: "달마시안", jp: "ダルメシアン" },
  { en: "Australian Cattle Dog", ko: "오스트레일리안 캐틀 독", jp: "オーストラリアン・キャトル・ドッグ" },
  { en: "English Bulldog", ko: "잉글리시 불독", jp: "イングリッシュ・ブルドッグ" },
  { en: "Bull Terrier", ko: "불 테리어", jp: "ブル・テリア" },
  { en: "Cane Corso", ko: "카네코르소", jp: "カネ・コルソ" },
  { en: "Dogo Argentino", ko: "도고 아르젠티노", jp: "ドゴ・アルヘンティーノ" },
  { en: "Japanese Spitz", ko: "재패니즈 스피츠", jp: "日本スピッツ" },
  { en: "Keeshond", ko: "키스혼드", jp: "キースホンド" },
  { en: "Leonberger", ko: "레온베르거", jp: "レオンベルガー" },
  { en: "Lowchen", ko: "로첸", jp: "レーシェン" },
  { en: "Norwegian Elkhound", ko: "노르웨이 엘크하운드", jp: "ノルウェー・エルクハウンド" },
  { en: "Portuguese Podengo", ko: "포르투갈 포덴고", jp: "ポルトガル・ポデンゴ" },
  { en: "Schipperke", ko: "스키퍼키", jp: "シッパーキ" },
  { en: "Skye Terrier", ko: "스카이 테리어", jp: "スカイ・テリア" },
  { en: "Xoloitzcuintli", ko: "숄로이츠퀸틀리", jp: "ショロイツクインツレ" },
  
  // --- Mixed & Special ---
  { en: "Maltipoo", ko: "말티푸", jp: "マルプー" },
  { en: "Cockapoo", ko: "코카푸", jp: "コッカプー" },
  { en: "Labradoodle", ko: "라브라도들", jp: "ラブラドゥードル" },
  { en: "Goldendoodle", ko: "골든두들", jp: "ゴールデンドゥードル" },
  { en: "Pomsky", ko: "폼스키", jp: "ポムスキー" },
  { en: "Puggle", ko: "퍼글", jp: "パグル" },
  { en: "Mixed Breed", ko: "믹스견", jp: "ミックス犬" },
  { en: "Abandoned Dog", ko: "유기견(품종모름)", jp: "保護犬(犬種不明)" },
  { en: "Other", ko: "기타", jp: "その他" }
];