export const DOG_PERSONALITIES = [
  { ko: "친화력 좋음", en: "Friendly", jp: "フレンドリー" },
  { ko: "낯가림 있음", en: "Shy", jp: "人見知り" },
  { ko: "에너지 넘침", en: "Energetic", jp: "元気いっぱい" },
  { ko: "얌전함", en: "Calm", jp: "穏やか" },
  { ko: "똑똑함", en: "Intelligent", jp: "賢い" },
  { ko: "고집셈", en: "Stubborn", jp: "頑固" },
  { ko: "애교 많음", en: "Affectionate", jp: "甘えん坊" },
  { ko: "독립적임", en: "Independent", jp: "독립的" },
  { ko: "겁이 많음", en: "Fearful", jp: "怖がり" },
  { ko: "호기심 왕성", en: "Curious", jp: "好奇心旺盛" },
  { ko: "활동적", en: "Active", jp: "アクティブ" },
  { ko: "장난꾸러기", en: "Playful", jp: "遊び好き" },
  { ko: "경계심 강함", en: "Protective", jp: "警戒心が強い" },
  { ko: "충성심 강함", en: "Loyal", jp: "忠実" },
  { ko: "온순함", en: "Gentle", jp: "優しい" },
  { ko: "용맹함", en: "Brave", jp: "勇敢" },
  { ko: "조용함", en: "Quiet", jp: "静か" },
  { ko: "자주 짖음", en: "Vocal", jp: "よく吠える" },
  { ko: "아이를 좋아함", en: "Loves kids", jp: "子供が好き" },
  { ko: "강아지 좋아함", en: "Loves dogs", jp: "犬が好き" },
  { ko: "고양이 좋아함", en: "Loves cats", jp: "猫が好き" },
  { ko: "식탐이 많음", en: "Food motivated", jp: "食いしん坊" },
  { ko: "장난감 집착", en: "Toy motivated", jp: "おもちゃ好き" },
  { ko: "훈련 잘됨", en: "Well-trained", jp: "しつけ済み" },
  { ko: "분리불안 있음", en: "Separation anxiety", jp: "分離不安" },
  { ko: "수영 좋아함", en: "Loves swimming", jp: "泳ぐのが好き" },
  { ko: "등산 잘함", en: "Good hiker", jp: "登山が得意" },
  { ko: "사회성 좋음", en: "Social", jp: "社交的" },
  { ko: "무심함", en: "Aloof", jp: "クール" },
  { ko: "인내심 강함", en: "Patient", jp: "辛抱強い" },
  { ko: "예민함", en: "Sensitive", jp: "敏感" },
  { ko: "적응력 좋음", en: "Resilient", jp: "適応力が高い" },
  { ko: "말 잘 들음", en: "Obedient", jp: "聞き分けがいい" },
  { ko: "산만함", en: "Distractible", jp: "落ち着きがない" },
  { ko: "사람을 좋아함", en: "Loves people", jp: "人が好き" },
  { ko: "영역 동물", en: "Territorial", jp: "縄張り意識が強い" },
  { ko: "잠이 많음", en: "Sleepy", jp: "よく寝る" },
  { ko: "질투 많음", en: "Jealous", jp: "嫉妬深い" },
  { ko: "깔끔함", en: "Clean", jp: "きれい好き" },
  { ko: "활동량 적음", en: "Low energy", jp: "運動量が少ない" }
];
