export const PORTRAIT_FILES = [
  "Afghan Hound.png",
  "Akita Inu.jpg",
  "Australian Cattle Dog.png",
  "Basenji.png",
  "Basset Hound.png",
  "Beagle.jpg",
  "Bernese Mountain Dog.jpg",
  "Bichon Frise.jpg",
  "Bloodhound.png",
  "Border Collie.jpg",
  "Borzoi.png",
  "Boxer.jpg",
  "Brittany.png",
  "Brussels Griffon.png",
  "Bulldog.jpg",
  "Bullmastiff.jpg",
  "Cane Corso.jpg",
  "Chihuahua.jpg",
  "Chinese Crested.png",
  "Chow Chow.jpg",
  "Cockapoo.png",
  "Cocker Spaniel.png",
  "Dachshund.jpg",
  "Dalmatian.png",
  "Doberman.jpg",
  "Dogo Argentino.png",
  "Donggyeongi.jpg",
  "English Bulldog.png",
  "English Cocker Spaniel.png",
  "English Setter.png",
  "French Bulldog.jpg",
  "German Shepherd.jpg",
  "German Shorthaired Pointer.png",
  "Giant Schnauzer.jpg",
  "Golden Retriever.jpg",
  "Goldendoodle.png",
  "Gordon Setter.png",
  "Great Dane.jpg",
  "Greater Swiss Mountain Dog.png",
  "Greyhound.png",
  "Hokkaido Ken.jpg",
  "Irish Setter.png",
  "Irish Wolfhound.png",
  "Italian Greyhound.png",
  "Jack Russell Terrier.png",
  "Japanese Chin.jpg",
  "Japanese Spitz.jpg",
  "Japanese Terrier.jpg",
  "Jindo Dog.jpg",
  "Kai Ken.jpg",
  "Keeshond.png",
  "Kishu Ken.jpg",
  "Labradoodle.png",
  "Labrador Retriever.jpg",
  "Leonberger.png",
  "Lowchen.png",
  "Maltese.jpg",
  "Maltipoo.png",
  "Mastiff.jpg",
  "Mixed Breed.png",
  "Newfoundland.jpg",
  "Norwegian Elkhound.png",
  "Pekingese.jpg",
  "Pharaoh Hound.png",
  "Pointer.png",
  "Pomeranian.jpg",
  "Pomsky.png",
  "Poodle.jpg",
  "Portuguese Podengo.png",
  "Portuguese Water Dog.jpg",
  "Pug.jpg",
  "Puggle.png",
  "Pungsan Dog.jpg",
  "Rhodesian Ridgeback.png",
  "Rottweiler.jpg",
  "Saint Bernard.jpg",
  "Saluki.png",
  "Samoyed.jpg",
  "Sapsali.jpg",
  "Schipperke.png",
  "Shar Pei.jpg",
  "Shiba Inu.jpg",
  "Shih Tzu.jpg",
  "Shikoku Ken.jpg",
  "Siberian Husky.jpg",
  "Silky Terrier.png",
  "Skye Terrier.png",
  "Springer Spaniel.png",
  "Standard Schnauzer.png",
  "Tibetan Spaniel.jpg",
  "Tibetan Terrier.jpg",
  "Tosa Inu.jpg",
  "Toy Fox Terrier.png",
  "Vizsla.png",
  "Weimaraner.png",
  "Welsh Corgi.jpg",
  "Whippet.png",
  "Xoloitzcuintli.png",
  "Yorkshire Terrier.jpg"
];
